spring:
    zipkin:
        base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0
zuul:
  routes:
    order:
      path: /myOrder/**
      serviceId: order
      #过滤敏感头默认过滤："Cookie", "Set-Cookie", "Authorization"
      sensitiveHeaders:
        - Authorization
    #简洁写法
    #order: /myOrder/**
    #排除某些路由
    ignored-patterns:
      - /**/product/listForOrder

feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true #超时熔断打开
        isolation:
          thread:
            timeoutInMilliseconds: 30000