server:
  port: 8101
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf-8&useSSL=false
status: false
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
logging:
  level:
    root: debug